config/routes.rb
Spina::Engine.routes.draw do
  # Backend
  namespace :admin, path: Spina.config.backend_path do
    root to: "pages#index"

    resource :account do
      member do
        get :style
        get :analytics
        get :social
      end
    end

    get "/settings/:plugin", to: "settings#edit", as: :edit_settings
    patch "/settings/:plugin", to: "settings#update", as: :settings

    resources :users

    # Sessions
    resources :sessions
    get "login" => "sessions#new"
    get "logout" => "sessions#destroy"

    # Passwords
    resources :password_resets

    # Media library
    get 'media_library' => 'images#index', as: "media_library"

    resources :pages do
      post :sort, on: :collection
    end

    resources :resources, only: [:show, :edit, :update]

    resources :navigations do
      post :sort, on: :member
    end

    resources :attachments do
      collection do
        get 'select/:page_part_id' => 'attachments#select', as: :select
        post 'insert/:page_part_id' => 'attachments#insert', as: :insert
        get 'select_collection/:page_part_id' => 'attachments#select_collection', as: :select_collection
        post 'insert_collection/:page_part_id' => 'attachments#insert_collection', as: :insert_collection
      end
    end

    resources :media_folders

    resources :images do
      collection do
        get 'folder/:id' => 'images#media_folder', as: :media_folder
        put 'folder/:id' => 'images#add_to_media_folder', as: :add_to_media_folder
      end
    end
    get :media_picker, to: 'media_picker#show'
    post :media_picker, to: 'media_picker#select'
  end

  # Sitemap
  resource :sitemap

  # Robots.txt
  get '/robots', to: 'pages#robots', constraints: { format: 'txt' }

  unless Spina.config.disable_frontend_routes
    # Frontend
    root to: "pages#homepage"

    # Pages
    get '/:locale/*id' => 'pages#show', constraints: {locale: /#{Spina.config.locales.join('|')}/ }
    get '/:locale/' => 'pages#homepage', constraints: {locale: /#{Spina.config.locales.join('|')}/ }
    get '/*id' => 'pages#show', as: "page", controller: 'pages', constraints: lambda { |request|
      (!(Rails.env.development? && request.env['PATH_INFO'].starts_with?('/rails/') || request.env['PATH_INFO'].starts_with?("/#{Spina.config.backend_path}") || request.env['PATH_INFO'].starts_with?('/attachments/'))) && request.path.exclude?("rails/active_storage")
    }
  end

end

app/models/spina/media_folder.rb
module Spina
  class MediaFolder < ApplicationRecord
    has_many :images, dependent: :nullify

    validates :name, presence: true, uniqueness: true
  end
end

app/controllers/spina/admin/media_folders_controller.rb
module Spina
  module Admin
    class MediaFoldersController < AdminController
      layout "spina/admin/media_library"

      def new
        @media_folder = MediaFolder.new
      end

      def show
        add_breadcrumb I18n.t('spina.website.media_library'), admin_media_library_path
        add_breadcrumb I18n.t('spina.website.images'), spina.admin_images_path
        @media_folder = MediaFolder.find(params[:id])
        add_breadcrumb @media_folder.name
        @images = @media_folder.images.sorted.page(params[:page])
      end

      def create
        @media_folder = MediaFolder.new(media_folder_params)
        @media_folder.save
        redirect_to spina.admin_images_path
      end

      def destroy
        @media_folder = MediaFolder.find(params[:id])
        @media_folder.destroy
        redirect_to spina.admin_images_path
      end

      private

        def media_folder_params
          params.require(:media_folder).permit(:name)
        end
    end
  end
end

app/views/spina/admin/media_folders/_form.html.haml
.modal
  %header
    = link_to '#', data: {dismiss: "modal"} do
      = icon('cross')
    %h3=t 'spina.photos.new_folder'

  = form_for [spina, :admin, @media_folder] do |f|
    %section
      = f.text_field :name, placeholder: Spina::MediaFolder.human_attribute_name(:name)
    %footer
      = link_to t('spina.cancel'), '#', data: {dismiss: 'modal'}
      = button_tag type: :submit, class: 'primary' do
        %i.icon.icon-plus{style: 'margin-right: 4px'}
        =t 'spina.photos.new_folder'

app/views/spina/admin/media_folders/_media_folder.html.haml
= link_to [:admin, media_folder], class: 'item media-folder', data: {add_to_media_folder_url: add_to_media_folder_admin_images_url(media_folder)} do
  .media-folder-thumbnail{data: {badge: media_folder.images.count}}
    - if media_folder.images.any?
      = image_tag variant(media_folder.images.last.file, resize: '144x144^', crop: "144x144+0+0")
    - else
      = image_tag 'spina/media_folder_placeholder.png'
    .media-folder-shadow
  .media-folder-name= media_folder.name

app/views/spina/admin/media_folders/new.js.erb
$("<%=j render 'form' %>").modal()

app/views/spina/admin/media_folders/show.html.haml
- content_for(:header_actions) do
  = link_to t('spina.photos.delete_folder'), spina.admin_media_folder_path(@media_folder), class: 'button button-danger button-link', style: "margin-right: 0", data: {method: :delete, confirm: t('spina.delete_confirmation', subject: @media_folder.name)}

.gallery-container
  .gallery
    .item
      = form_with model: [:admin, Spina::Image.new], id: 'new_image', class: 'new_image' do |f|
        = f.submit style: 'display: none'
        = hidden_field_tag :media_library, value: @media_folder.id
        = f.label :file, t('spina.images.upload')
        = f.file_field :files, multiple: true, data: {direct_upload_url: main_app.rails_direct_uploads_url, customfileinput: true}

    .gallery-prepend-image
      .infinite-scroll
        = render partial: 'spina/admin/images/image', collection: @images

      .infinite-pagination{data: {controller: 'infinite-scroll'}}= link_to_next_page @images, 'Next', remote: true, data: {target: "infinite-scroll.link"}