config/routes.rb
Spina::Engine.routes.draw do
  # Backend
  namespace :admin, path: Spina.config.backend_path do
    root to: "pages#index"

    resource :account do
      member do
        get :style
        get :analytics
        get :social
      end
    end

    get "/settings/:plugin", to: "settings#edit", as: :edit_settings
    patch "/settings/:plugin", to: "settings#update", as: :settings

    resources :users

    # Sessions
    resources :sessions
    get "login" => "sessions#new"
    get "logout" => "sessions#destroy"

    # Passwords
    resources :password_resets

    # Media library
    get 'media_library' => 'images#index', as: "media_library"

    resources :pages do
      post :sort, on: :collection
    end

    resources :resources, only: [:show, :edit, :update]

    resources :navigations do
      post :sort, on: :member
    end

    resources :attachments do
      collection do
        get 'select/:page_part_id' => 'attachments#select', as: :select
        post 'insert/:page_part_id' => 'attachments#insert', as: :insert
        get 'select_collection/:page_part_id' => 'attachments#select_collection', as: :select_collection
        post 'insert_collection/:page_part_id' => 'attachments#insert_collection', as: :insert_collection
      end
    end

    resources :media_folders

    resources :images do
      collection do
        get 'folder/:id' => 'images#media_folder', as: :media_folder
        put 'folder/:id' => 'images#add_to_media_folder', as: :add_to_media_folder
      end
    end
    get :media_picker, to: 'media_picker#show'
    post :media_picker, to: 'media_picker#select'
  end

  # Sitemap
  resource :sitemap

  # Robots.txt
  get '/robots', to: 'pages#robots', constraints: { format: 'txt' }

  unless Spina.config.disable_frontend_routes
    # Frontend
    root to: "pages#homepage"

    # Pages
    get '/:locale/*id' => 'pages#show', constraints: {locale: /#{Spina.config.locales.join('|')}/ }
    get '/:locale/' => 'pages#homepage', constraints: {locale: /#{Spina.config.locales.join('|')}/ }
    get '/*id' => 'pages#show', as: "page", controller: 'pages', constraints: lambda { |request|
      (!(Rails.env.development? && request.env['PATH_INFO'].starts_with?('/rails/') || request.env['PATH_INFO'].starts_with?("/#{Spina.config.backend_path}") || request.env['PATH_INFO'].starts_with?('/attachments/'))) && request.path.exclude?("rails/active_storage")
    }
  end

end

app/controllers/spina/admin/media_picker_controller.rb
module Spina
  module Admin
    class MediaPickerController < AdminController

      def show
        @images = Image.page(params[:page])

        if params[:selected_ids].present?
          ids = params[:selected_ids].map(&:to_i).join(', ')
          @images = @images.order(Arel.sql("CASE WHEN id IN(#{ids}) THEN 0 ELSE 1 END, created_at DESC"))
        else
          @images = @images.sorted
        end

        render params[:page].present? ? :infinite_scroll : :show
      end

      def select
        if params[:multiple]
          @images = Image.where(id: params[:image_ids])
        else 
          @image = Image.find(params[:image_id])
        end
      end

    end
  end
end

app/views/spina/admin/media_picker/_modal.html.haml
.modal.modal-large
  %section
    .gallery-select.gallery{data: {multiselect: defined?(multiple) && multiple}}
      .item.item-small.item-uploader.new-image-form
        = render partial: 'spina/admin/images/form'

      = form_with url: admin_media_picker_path, class: 'gallery-prepend-image' do
        = hidden_field_tag :hidden_field_id, params[:hidden_field_id]
        = hidden_field_tag :trix_editor_id, params[:trix_editor_id]
        = check_box_tag :multiple, true, defined?(multiple) && multiple, style: 'display: none'

        .infinite-scroll
          = render partial: 'spina/admin/images/image', collection: @images

        .infinite-pagination{data: {controller: 'infinite-scroll'}}= link_to_next_page @images, 'Next', params: params, remote: true, data: {target: "infinite-scroll.link"}

        - if defined?(multiple) && multiple
          .gallery-select-action-bar
            .pull-right
              = link_to t('spina.cancel'), "#", class: 'button button-link', data: {dismiss: 'modal'}
              = button_tag type: 'submit', class: 'button button-primary button-large', style: 'margin-bottom: 0px' do
                = icon('plus')
                = t('spina.images.choose_images')
                %span.gallery-select-counter
                  - if params[:selected_ids].try(:any?)
                    (#{ params[:selected_ids].count })

app/views/spina/admin/media_picker/infinite_scroll.js.erb
// Append new data
$("<%=j render partial: 'spina/admin/images/image', collection: @images %>").appendTo($(".infinite-scroll"));

// Update pagination link
$('.infinite-pagination').html("<%= j link_to_next_page @images, 'Next', params: params.slice(:selected_photo_id).permit(:selected_photo_id), remote: true, data: {target: 'infinite-scroll.link'} %>")

app/views/spina/admin/media_picker/select.js.erb
let hidden_input = $("input[data-hidden-field-id='<%= j params[:hidden_field_id] %>']");
hidden_input.parents('.media_picker').find('.image').remove();
hidden_input.val("");

<% if @image.present? %>
  hidden_input.parents('.media_picker').append("<%=j render partial: 'spina/admin/images/image', object: @image, locals: {simple: true} %>");
  hidden_input.val("<%= @image.id %>");

  // Trix editor
  $('#<%= params[:trix_editor_id] %>').trigger('image-insert', '<%= main_app.url_for(@image.variant(resize: "800x800")) %>');
  $.hideModal();
<% end %>

<% if @images.present? %>
  let image_collection = $("<%= j render partial: 'spina/admin/image_collections/image_collection', locals: {images: @images} %>");
  hidden_input.parents('.horizontal-form-content').find('.image-collection').html(image_collection);
  hidden_input.val("<%= @images.map(&:id).join(',') %>");
<% end %>

$('.sortable-grid').sortable().bind('sortupdate', function(e) {
  position_array = [];
  $(e.target).find('li.image').each(function(index) {
    position_array.push($(this).data('image-id'));
  });
  $(e.target).parents('.horizontal-form-content').find('.images-positions').val(position_array.join(","));
});
$('.sortable-grid').trigger('sortupdate');

$.hideModal();

app/views/spina/admin/media_picker/show.js.erb
$("<%=j render partial: 'modal', locals: {multiple: params[:multiple]} %>").modal();